name: ndef_record
description: A Dart package that provides an implementation of the NFC Data Exchange Format (NDEF).
repository: https://github.com/okadan/flutter-nfc-manager/tree/main/packages/ndef_record
version: 1.2.1
resolution: workspace

environment:
  sdk: ^3.6.2

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^5.0.0
