name: nfc_manager_ndef
description: A Flutter package that provides NDEF abstraction using nfc_manager plugin.
repository: https://github.com/okadan/flutter-nfc-manager/tree/main/packages/nfc_manager_ndef
version: 1.0.1
resolution: workspace

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: #^4.0.2
    git: 
      url: https://github.com/pai-r-k-kamada/flutter-nfc-manager # ←フォークしてできたリポジトリ
      #ref: v4.0.2 # ←ブランチ
      path: packages/nfc_manager/ # ←パス  

dev_dependencies:
  lints: ^5.0.0
